environment:
  matrix:
    - PYTHON_VERSION: 3.7
      MINICONDA: "C:\\Miniconda37"

image: Visual Studio 2019

platform: x64

install:
  - set PATH=C:\Miniconda38-x64;C:\Miniconda38-x64\Scripts;%PATH%
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda
  - cmd: conda info -a
  - cmd: conda env create -f ./environment.yml
  - activate weldx

build: false

test_script:
  - pytest