---
engines:
  bandit:
    exclude_paths:
      - tests/**

  duplication:
    enabled: true
    exclude_paths:
      - tests/**

exclude_paths:
  - 'docs/**'
  - 'versioneer.py'
  - 'weldx/_version.py'
  - 'scripts/**'
  - 'CHANGELOG.md'
