---
engines:
  bandit:
    exclude_paths:
      - tests/**

  duplication:
    enabled: true
    exclude_paths:
      - tests/**

exclude_paths:
  - 'doc/**'
  - 'versioneer.py'
  - 'weldx/_version.py'
  - 'scripts/**'
  - 'CHANGELOG.md'
  - '.github/pull_request_template.md'
