version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

exclude_patterns = [
  "doc/**",
  "versioneer.py",
  "scripts/**",
  "weldx/_version.py",
  "weldx/asdf/**",
]

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x.x"