version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

exclude_patterns = [
  "docs/**",
  ".vulture_whitelist.py",
  "versioneer.py",
  "weldx/_version.py",
  "weldx/asdf/**",
  "scripts/validate_shapes.py"
]

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x.x"