version = 1

test_patterns = [
  "weldx/tests/**",
  "test_*.py"
]

exclude_patterns = [
  "doc/**",
  "scripts/**",
  "weldx/_version.py",
  "weldx/asdf/**",
  "weldx/tags/**",
]

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x.x"

[analyzers.meta]
# skip magic and private objects: https://discuss.deepsource.io/t/docstrings-for-private-classes-methods/259/2
skip_doc_coverage = ["magic", "nonpublic"]
