ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: false
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: monthly
  skip: []
  submodules: false
exclude: '.*.weldx$|.*.wx$|.*.asdf$'
repos:
  # ----- general formatting -----
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: devtools/conda.recipe/meta.yaml  # doesn't play nice with jinja
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
          - mdformat-config
  # ----- Python formatting -----
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.239
    hooks:
      - id: ruff
        args:
          - --quiet
          - --fix
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.11
    hooks:
      - id: validate-pyproject
  # ----- Jupyter Notebooks -----
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
      - id: nbqa-black
      - id: nbqa-ruff  # ruff handles isort
        args:
          - --fix
          - --force-exclude
  - repo: https://github.com/roy-ht/pre-commit-jupyter
    rev: v1.2.1
    hooks:
      - id: jupyter-notebook-cleanup
        args:
          - --remove-kernel-metadata
  # ----- spellchecking -----
  - repo: https://github.com/codespell-project/codespell/
    rev: v2.2.2
    hooks:
      - id: codespell
        exclude: doc/src/legal-notice.md
        args:
          - -L ro
