ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: false
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: monthly
  skip: []
  submodules: false
exclude: '.*.weldx$|.*.wx$|.*.asdf$'
repos:
  # ----- general formatting -----
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: devtools/conda.recipe/meta.yaml  # doesn't play nice with jinja
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
          - mdformat-config
  # ----- Python formatting -----
  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: v1.0
    hooks:
    - id: upgrade-type-hints
      args: [ '--futures=true' ]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
            'flake8-bugbear==22.10.27',
            'flake8-coding==1.3.2',
            'flake8-comprehensions==3.10.1',
            'flake8-deprecated==2.0.1',
            'flake8-print==5.0.0',
#            'flake8-quotes==3.3.1',
        ]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        files: '^weldx/'
        additional_dependencies: ["toml"]
        exclude: |
          (?x)^(
            ^weldx/tags|
            ^weldx/tests|
            ^weldx/asdf|
            .*__.*.py
          )
        args:
          - --convention=numpy
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.118
    hooks:
      - id: ruff
        args:
          - --quiet
          - --fix
  # ----- Jupyter Notebooks -----
  - repo: https://github.com/marscher/nbQA
    rev: db86f8233998682e367d436eceec7cd4776cf334
    hooks:
      - id: nbqa-black
      - id: nbqa-isort
      - id: nbqa-ruff
  - repo: https://github.com/roy-ht/pre-commit-jupyter
    rev: v1.2.1
    hooks:
      - id: jupyter-notebook-cleanup
        args:
          - --remove-kernel-metadata
  # ----- spellchecking -----
  - repo: https://github.com/codespell-project/codespell/
    rev: v2.2.2
    hooks:
      - id: codespell
        exclude: doc/legal-notice.rst
        args:
          - -L ro
