# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# RTD build env
build:
  os: ubuntu-24.04
  tools:
      python: "latest"
  jobs:
    post_checkout:
      - git fetch --unshallow
    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
    install:
      - pixi install -e docs
    build:
      html:
      - pixi run -e docs docs_full