dictionaries:
  - en
  - en_GB

excluded_files:
  - ".*"
  - "docs*"
  - "environment.yml"
  - "tools*"

excluded_words:
  - typoci
  # python packages -----------------------------
  - numpy
  - pandas
  - xarray
  - scipy
  - pytest
  - pydocstyle
  - matplotlib
  - networkx
  # matplotlib ----------------------------------
  - pyplot
  - gca
  - plt
  # flake8 --------------------------------------
  - noqa
  # numpy ---------------------------------------
  - arange
  - allclose
  - det
  - dtype
  - hstack
  - isclose
  - linalg
  - matmul
  - ndarray
  - ndim
  - vstack
  # pandas --------------------------------------
  - isin
  - isnan
  - fillna
  # jupyter notebooks ---------------------------
  - jupyter
  - nbformat
  # iPython -------------------------------------
  - ipynb
  - ipywidgets
  - ipython
  # other ---------------------------------------
  - linearization
  - coords