dictionaries:
  - en
  - en_GB

excluded_files:
  - ".*"
  - "docs*"
  - "environment.yml"
  - "tools*"

excluded_words:
  - typoci
  # python packages -----------------------------
  - asdf
  - numpy
  - pandas
  - xarray
  - scipy
  - pytest
  - pydocstyle
  - matplotlib
  - versioneer
  # matplotlib ----------------------------------
  - pyplot
  - gca
  - plt
  # flake8 --------------------------------------
  - noqa
  - addopts
  # asdf ----------------------------------------
  - yamlutil
  # numpy ---------------------------------------
  - linalg
  - ndim
  - dtype
  - isclose
  - ndarray
  - hstack
  - matmul
  - arange
  - det
  - vstack
  - dtypes
  # pandas --------------------------------------
  - isin
  - iloc
  - timedelta
  - timedeltaindex
  - datetimeindex
  - isoformat
  # jupyter notebooks ---------------------------
  - jupyter
  - nbformat
  # iPython -------------------------------------
  - ipynb
  - ipywidgets
  - ipython
  # welding -------------------------------------
  - weldment
  # conda ---------------------------------------
  - conda
  - noarch
  # other ---------------------------------------
  - linearization
  - ureg
  - Cagtay
  - Fabry
