dictionaries:
  - en
  - en_GB

excluded_files:
  - ".*"
  - "docs*"
  - "environment.yml"
  - "tools*"
  - "versioneer.py"
  - "weldx/_version.py"

excluded_words:
  - typoci
  # weldx ---------------------------------------
  - LocalCoordinateSystem
  # python packages -----------------------------
  - asdf
  - numpy
  - pandas
  - xarray
  - scipy
  - sympy
  - pytest
  - pydocstyle
  - matplotlib
  - versioneer
  - isort
  - networkx
  - shutil
  - functools
  - boltons
  - meshio
  - pytest-xdist
  - nbval
  # matplotlib ----------------------------------
  - gca
  - mpl
  - ncols
  - plt
  - pyplot
  - zorder
  # flake8 --------------------------------------
  - noqa
  - addopts
  # asdf ----------------------------------------
  - tagname
  - yamlutil
  # numpy ---------------------------------------
  - arange
  - allclose
  - atol
  - det
  - dtype
  - hstack
  - isclose
  - issubdtype
  - linalg
  - matmul
  - ndarray
  - ndarrays
  - ndim
  - newaxis
  - tolist
  - vstack
  # pandas / xarray -----------------------------
  - bfill
  - ffill
  - idxmax
  - idxmin
  - isel
  - iloc
  - isin
  - isnan
  - ffill
  - fillna
  - sel
  - dtypes
  - timedelta
  - timedeltaindex
  - datetimeindex
  - isoformat
  # pyfilesystem --------------------------------
  - osfs
  - memoryfs
  # pytest --------------------------------------
  - conftest
  - addoption
  - xfail
  # jupyter notebooks ---------------------------
  - jupyter
  - nbformat
  # iPython -------------------------------------
  - ipynb
  - ipywidgets
  - ipython
  - jslink
  # scipy ---------------------------------------
  - Slerp
  - rotvec
  - quat
  # sympy ---------------------------------------
  - lambdify
  - sympify
  # welding -------------------------------------
  - weldment
  - GmawProcess
  - GmawProcessTypeAsdf
  - CLOOS
  - Quinto
  # conda ---------------------------------------
  - conda
  - noarch
  # deepsource ----------------------------------
  - skipcq
  # documentation -------------------------------
  - readthedocs
  - recommonmark
  - nbsphinx
  - mathjax
  - toctree
  - numpydoc
  # markdown / latex ----------------------------
  - cdot
  # file extensions -----------------------------
  - vtk
  - stl
  # other ---------------------------------------
  - addopts
  - csm
  - coords
  - devdoc
  - dsx
  - dtypes
  - interp
  - linearization
  - ureg
  - Cagtay
  - Fabry
  - Pittner
  - xyz
  - bamwelding
  - netcdf
  - msm
  - Fronius
  - gmaw
  - feedrate
  - Beckhoff
  - unmerge
  - itertools
  - rst
  - pycharm
  - tslibs
  - quickstart
  - nsecond
  - iterutils
  - pyproject
  - pyargs
  - argnames
  - argvalues
  # German ---------------------------------------
  - Bundesanstalt
  - für
  - Materialforschung
  - und
  - prüfung
