dictionaries:
  - en
  - en_GB

excluded_files:
  - ".*"
  - "docs*"
  - "environment.yml"
  - "tools*"
  - "versioneer.py"
  - "weldx/_version.py"

excluded_words:
  - typoci
  # weldx ---------------------------------------
  - LocalCoordinateSystem
  # python packages -----------------------------
  - asdf
  - numpy
  - pandas
  - xarray
  - scipy
  - sympy
  - pytest
  - pydocstyle
  - matplotlib
  - versioneer
  - isort
  - networkx
  - shutil
  # matplotlib ----------------------------------
  - pyplot
  - gca
  - plt
  # flake8 --------------------------------------
  - noqa
  - addopts
  # asdf ----------------------------------------
  - tagname
  - yamlutil
  # numpy ---------------------------------------
  - arange
  - allclose
  - atol
  - det
  - dtype
  - hstack
  - isclose
  - issubdtype
  - linalg
  - matmul
  - ndarray
  - ndim
  - newaxis
  - vstack
  # pandas / xarray -----------------------------
  - bfill
  - ffill
  - idxmax
  - idxmin
  - isel
  - iloc
  - isin
  - isnan
  - ffill
  - fillna
  - sel
  - dtypes
  - timedelta
  - timedeltaindex
  - datetimeindex
  - isoformat
  # pytest --------------------------------------
  - conftest
  - addoption
  - xfail
  # jupyter notebooks ---------------------------
  - jupyter
  - nbformat
  # iPython -------------------------------------
  - ipynb
  - ipywidgets
  - ipython
  # scipy ---------------------------------------
  - Slerp
  - rotvec
  - quat
  # sympy ---------------------------------------
  - lambdify
  - sympify
  # welding -------------------------------------
  - weldment
  - GmawProcess
  - GmawProcessTypeAsdf
  - CLOOS
  - Quinto
  # conda ---------------------------------------
  - conda
  - noarch
  # documentation -------------------------------
  - readthedocs
  - recommonmark
  - nbsphinx
  - mathjax
  - toctree
  - numpydoc
  # markdown / latex ----------------------------
  - cdot
  # other ---------------------------------------
  - addopts
  - csm
  - coords
  - dsx
  - dtypes
  - interp
  - isort
  - linearization
  - ureg
  - Cagtay
  - Fabry
  - xyz
  - bamwelding
  - netcdf
  - msm
  - Fronius
  - gmaw
  - feedrate
  - Beckhoff
  - unmerge
  - itertools
  - rst
  - pycharm
  - tslibs
