dictionaries:
  - en
  - en_GB

excluded_files:
  - ".*"
  - "docs*"
  - "environment.yml"
  - "tools*"

excluded_words:
  - typoci
  # python packages -----------------------------
  - numpy
  - pandas
  - xarray
  - scipy
  - pytest
  - pydocstyle
  - matplotlib
  - networkx
  # matplotlib ----------------------------------
  - pyplot
  - gca
  - plt
  # flake8 --------------------------------------
  - noqa
  # numpy ---------------------------------------
  - arange
  - allclose
  - atol
  - det
  - dtype
  - hstack
  - isclose
  - linalg
  - matmul
  - ndarray
  - ndim
  - newaxis
  - vstack
  # pandas / xarray -----------------------------
  - isel
  - isin
  - isnan
  - fillna
  - sel
  # jupyter notebooks ---------------------------
  - jupyter
  - nbformat
  # iPython -------------------------------------
  - ipynb
  - ipywidgets
  - ipython
  # other ---------------------------------------
  - addopts
  - csm
  - coords
  - isort
  - linearization
  - xyz
