dictionaries:
  - en
  - en_GB

excluded_files:
  - ".*"
  - "docs*"
  - "environment.yml"
  - "tools*"
  - "versioneer.py"
  - "weldx/_version.py"

excluded_words:
  - typoci
  # python packages -----------------------------
  - asdf
  - numpy
  - pandas
  - xarray
  - scipy
  - pytest
  - pydocstyle
  - matplotlib
  - versioneer
  - isort
  - networkx
  # matplotlib ----------------------------------
  - pyplot
  - gca
  - plt
  # flake8 --------------------------------------
  - noqa
  - addopts
  # asdf ----------------------------------------
  - yamlutil
  # numpy ---------------------------------------
  - arange
  - allclose
  - atol
  - det
  - dtype
  - hstack
  - isclose
  - linalg
  - matmul
  - ndarray
  - ndim
  - newaxis
  - vstack
  # pandas / xarray -----------------------------
  - bfill
  - ffill
  - idxmax
  - idxmin
  - isel
  - iloc
  - isin
  - isnan
  - ffill
  - fillna
  - sel
  - dtypes
  - timedelta
  - timedeltaindex
  - datetimeindex
  - isoformat
  # jupyter notebooks ---------------------------
  - jupyter
  - nbformat
  # iPython -------------------------------------
  - ipynb
  - ipywidgets
  - ipython
  # scipy ---------------------------------------
  - Slerp
  # welding -------------------------------------
  - weldment
  # conda ---------------------------------------
  - conda
  - noarch
  # other ---------------------------------------
  - addopts
  - csm
  - coords
  - dsx
  - dtypes
  - interp
  - isort
  - linearization
  - ureg
  - Cagtay
  - Fabry
  - xyz
  - bamwelding
