{% set pyproject = load_file_data('pyproject.toml') %}
{% set proj = pyproject.get('project') %}

package:
  name: weldx
  version: {{ proj.get('version') }}

source:
    path: ../..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    # TODO: check this only used to be console script entry points, why not ASDF?
  {% for e in proj.get('entry_points') %}
    - {{ e }}
  {% endfor %}
requirements:
  host:
    - pip
    - setuptools_scm
    - python
  run:
    - python {{ proj.get("requires-python") }}
    # dependencies are defined in pyproject.toml
    {% for dep in proj.get('dependencies') %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  requires:
    - pip
    - pytest
    - pytest-xdist
    - black
    # requires wx-widgets here, so we can properly load the visualization sub-package.
    - weldx_widgets
  files:
    - conftest.py
  imports:
    - weldx
    - weldx.visualization
  commands:
    - pip check
    - welding_schema --help
    - pytest --pyargs weldx.tests -n auto --dist=loadfile --tb=short --color=yes

about:
  home: https://www.bam.de/Content/EN/Projects/WelDX/weldx.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python API for the WelDX file format and standard
  description: |
    Scientific welding data covers a wide range of physical domains and
    timescales and are measured using various different sensors. Complex and
    highly specialized experimental setups at different welding institutes
    complicate the exchange of welding research data further.

    The WelDX research project aims to foster the exchange of scientific data
    inside the welding community by developing and establishing a new open
    source file format suitable for documentation of experimental welding data
    and upholding associated quality standards. In addition to fostering
    scientific collaboration inside the national and international welding
    community an associated advisory committee will be established to oversee
    the future development of the file format. The proposed file format will be
    developed with regard to current needs of the community regarding
    interoperability, data quality and performance and will be published under
    an appropriate open source license. By using the file format objectivity,
    comparability and reproducibility across different experimental setups can
    be improved.
  doc_url: https://weldx.readthedocs.io
  dev_url: https://github.com/BAMWelDX/weldx/

extra:
  recipe-maintainers:
    - marscher
    - vhirtham
    - CagtayFabry
