name: weldx
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - setuptools_scm
  - numpy>=1.18
  - pandas>=1.0
  - scipy<1.6
  - sympy>=1.6
  - xarray>=0.15
  - pint>=0.11
  - bottleneck
  - boltons
  - asdf>=2.8
  - openpyxl
  - fs
  - meshio
  # graph packages
  - networkx
  # Code quality
  - codecov
  - pytest
  - pytest-cov
  - pytest-xdist
  - nbval
  - ruff
  - black
  - nbqa
  # Plotting
  - ipykernel
  - ipympl
  - k3d
  - line_profiler
  - matplotlib
  - memory_profiler
  - seaborn
  - snakeviz
  # documentation
  - sphinx
  - recommonmark
  - sphinxcontrib-napoleon
  - nbsphinx
  - sphinx-copybutton
  - pydata-sphinx-theme
  - numpydoc>=0.5
  - sphinx-autodoc-typehints
  # pip packages
  - pip
  - pip:
    - git+https://github.com/CagtayFabry/sphinx-asdf.git@sphinx-weldx
