name: weldx
channels:
  - conda-forge
dependencies:
  - python=3.12
  - setuptools_scm
  - numpy>=1.20
  - pandas>=1.5,<3
  - scipy>=1.6.2,<1.17
  - sympy>=1.6
  - xarray>=2022.9
  - pint>=0.21
  - pint-xarray>=0.3,<0.5
  - bottleneck>=1.3.3
  - boltons
  - bidict
  - decorator
  - packaging
  - pyyaml
  - asdf>=2.15.1
  - fs
  - meshio
  # graph packages
  - networkx
  # Code quality
  - codecov
  - pytest
  - pytest-cov
  - pytest-xdist
  - nbval
  - ruff
  - nbqa
  # Plotting (weldx.plot extra)
  - ipykernel
  - ipympl
  - k3d
  - matplotlib
  - line_profiler
  - memory_profiler
  - seaborn
  - snakeviz
  # media extra
  - av
  - dask-image
  - pillow
  - tifffile
  # documentation
  - sphinx>=4.1.1,==7.2
  - sphinx-copybutton==0.5
  - pydata-sphinx-theme<0.15
  - numpydoc>=0.5
  - sphinx-autodoc-typehints>=1.21.8,==2
  - ipywidgets
  - myst-parser
  - urllib3<2
  # pip packages
  - pip
  - pip:
    - myst-nb-json
