%YAML 1.1
---
id: asdf://weldx.bam.de/weldx/manifests/weldx-0.1.0
extension_uri: asdf://weldx.bam.de/weldx/extensions/weldx-0.1.0
title: weldx extension manifest for tag mapping
description: Manifest listing all tag URIs with schema URIs supported by weldx
tags:
- tag_uri: tag:stsci.edu:asdf/unit/quantity-1.1.0
  schema_uri: http://stsci.edu/schemas/asdf/unit/quantity-1.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/uuid-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/uuid-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/aws/design/base_metal-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/aws/design/base_metal-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/aws/design/connection-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/aws/design/connection-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/aws/design/joint_penetration-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/aws/design/joint_penetration-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/aws/design/sub_assembly-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/aws/design/sub_assembly-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/aws/design/weldment-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/aws/design/weldment-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/aws/design/weld_details-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/aws/design/weld_details-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/aws/design/workpiece-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/aws/design/workpiece-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/aws/process/arc_welding_process-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/aws/process/arc_welding_process-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/aws/process/gas_component-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/aws/process/gas_component-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/aws/process/shielding_gas_for_procedure-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/aws/process/shielding_gas_for_procedure-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/aws/process/shielding_gas_type-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/aws/process/shielding_gas_type-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/dataset-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/dataset-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/data_array-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/data_array-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/dimension-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/dimension-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/file-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/file-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/mathematical_expression-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/mathematical_expression-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/time_series-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/time_series-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/variable-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/variable-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/geometry/spatial_data-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/geometry/spatial_data-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/graph/di_edge-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/graph/di_edge-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/graph/di_graph-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/graph/di_graph-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/graph/di_node-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/graph/di_node-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/transformations/coordinate_system_hierarchy-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/transformations/coordinate_system_hierarchy-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/transformations/local_coordinate_system-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/transformations/local_coordinate_system-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/core/transformations/rotation-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/core/transformations/rotation-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/debug/test_property_tag-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/debug/test_property_tag-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/debug/test_shape_validator-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/debug/test_shape_validator-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/debug/test_unit_validator-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/debug/test_unit_validator-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/equipment/measurement_equipment-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/equipment/measurement_equipment-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/groove/iso_9692_1_2013_12/DHUGroove-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/groove/iso_9692_1_2013_12/DHUGroove-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/groove/iso_9692_1_2013_12/DHVGroove-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/groove/iso_9692_1_2013_12/DHVGroove-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/groove/iso_9692_1_2013_12/DUGroove-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/groove/iso_9692_1_2013_12/DUGroove-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/groove/iso_9692_1_2013_12/DVGroove-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/groove/iso_9692_1_2013_12/DVGroove-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/groove/iso_9692_1_2013_12/FFGroove-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/groove/iso_9692_1_2013_12/FFGroove-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/groove/iso_9692_1_2013_12/HUGroove-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/groove/iso_9692_1_2013_12/HUGroove-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/groove/iso_9692_1_2013_12/HVGroove-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/groove/iso_9692_1_2013_12/HVGroove-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/groove/iso_9692_1_2013_12/IGroove-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/groove/iso_9692_1_2013_12/IGroove-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/groove/iso_9692_1_2013_12/UGroove-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/groove/iso_9692_1_2013_12/UGroove-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/groove/iso_9692_1_2013_12/UVGroove-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/groove/iso_9692_1_2013_12/UVGroove-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/groove/iso_9692_1_2013_12/VGroove-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/groove/iso_9692_1_2013_12/VGroove-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/groove/iso_9692_1_2013_12/VVGroove-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/groove/iso_9692_1_2013_12/VVGroove-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/measurement/error-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/measurement/error-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/measurement/measurement-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/measurement/measurement-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/measurement/measurement_chain-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/measurement/measurement_chain-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/measurement/signal-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/measurement/signal-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/measurement/signal_transformation-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/measurement/signal_transformation-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/measurement/source-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/measurement/source-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/process/GMAW-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/process/GMAW-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/process/CLOOS/pulse-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/process/CLOOS/pulse-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/process/CLOOS/spray_arc-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/process/CLOOS/spray_arc-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/time/datetimeindex-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/time/datetimeindex-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/time/time-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/time/time-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/time/timedelta-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/time/timedelta-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/time/timedeltaindex-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/time/timedeltaindex-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/time/timestamp-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/time/timestamp-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/units/quantity-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/units/quantity-0.1.0
- tag_uri: asdf://weldx.bam.de/weldx/tags/units/units-0.1.0
  schema_uri: asdf://weldx.bam.de/weldx/schemas/units/units-0.1.0
...
