{% set data = load_setup_py_data() %}

package:
    name: weldx
    version: {{ data["version"] }}

source:
    path: ..

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0
  noarch: python

requirements:
    build:
        - python
        - setuptools
        - setuptools_scm
    run:
        - python
        # dependencies are defined in setup.py
        {% for dep in data['install_requires'] %}
        - {{ dep.lower() }}
        {% endfor %}

test:
    imports:
        - weldx

about:
    home: www.bam.de/weldx
    license: BSD
