{% set data = load_setup_py_data() %}

package:
    name: weldx
    version: {{ data["version"] }}

source:
    path: ..

build:
  script: pip install . -v
  number: 0
  noarch: python

requirements:
    host:
        - python >=3.8
        - pip
        - setuptools_scm
    run:
        - python >=3.8
        # dependencies are defined in setup.py
        {% for dep in data['install_requires'] %}
        - {{ dep.lower() }}
        {% endfor %}

test:
    imports:
        - weldx
        - weldx.visualization

about:
    home: www.bam.de/weldx
    license: BSD
