name: Changelog

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]
    branches:
      - master

jobs:
  changelog:
    if: |
      !contains(github.event.pull_request.labels.*.name, 'no-changelog-entry-needed') &&
      github.event.pull_request.draft == false
    name: Confirm changelog entry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Grep for PR number in CHANGELOG.md
        run: grep -P '\[[^\]]*#${{github.event.number}}[,\]]' CHANGELOG.md
