name: check notebooks

on:
  pull_request:
    branches:
    - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
