name: conda build
on:
  # Trigger the workflow on push events on master
  push:
    branches:
      - master
  # Trigger the workflow on relevant pull request events
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  # Trigger the workflow on all release created events (this could redirect to main conda channel)
  release:
    types:
      - created

jobs:
  build:
    if: github.event.pull_request.draft == false # exclude job from draft PR
    name: conda build (local)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --prune --tags # Fetch all history for all tags and branches

      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if ./conda.recipe/build_env.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('./conda.recipe/build_env.yml') }}

      - name: Setup Conda Environment
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          environment-file: ./conda.recipe/build_env.yml
          activate-environment: build_env
          channels: conda-forge
          auto-activate-base: false
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: conda info
        shell: bash -l {0}
        run: conda info

      - name: conda list
        shell: bash -l {0}
        run: conda list

      - name: Build from local conda recipe
        shell: bash -l {0}
        run: conda build .

      - name: set package file env
        shell: bash -l {0}
        run: echo ::set-env name=PACKAGE_DIR::$(conda build . --output)

      - uses: actions/upload-artifact@v2
        with:
          path: ${{ env.PACKAGE_DIR }}

      - name: upload package to dev label on Anaconda Cloud
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash -l {0}
        env: # set access token from GitHub secrets
          anaconda_token: ${{ secrets.Anaconda_BAMwelding }}
        run: |
          anaconda -t $anaconda_token upload --user BAMwelding --label dev $PACKAGE_DIR
