name: pydocstyle
on: [push]

jobs:
  pydocstyle:
    name: pydocstyle
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        py: [ '3.7', '3.8' ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: pip installs
        run: pip install pydocstyle==5.*
      - name: run pydocstyle
        run: |
          pydocstyle

  flake8:
    name: flake8
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        py: [ '3.7', '3.8' ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: pip installs
        run: pip install flake8==3.7.*
      - name: run flake8
        run: |
          flake8

  flake8-docstrings:
    name: flake8-docstrings
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        py: [ '3.7', '3.8' ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: pip installs
        run: pip install flake8==3.7.* pydocstyle==5.* flake8-docstrings
      - name: run flake8
        run: |
          flake8