name: pydocstyle
on: [push]

jobs:
  pydocstyle:
    name: pydocstyle
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: pip installs
        run: pip install pydocstyle
      - name: run pydocstyle
        run: |
          pydocstyle

  flake8:
    name: flake8
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: pip installs
        run: pip install flake8
      - name: run flake8
        run: |
          flake8

  flake8-docstrings:
    name: flake8-docstrings
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: pip installs
        run: pip install flake8 pydocstyle flake8-docstrings
      - name: run flake8
        run: |
          flake8