name: pytest
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  event_file:
    name: "Upload PR Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: Event File
          path: ${{ github.event_path }}

  pytest:
    name: pytest (${{ matrix.os }}, ${{ matrix.environment }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        environment:
          - test-py310
          - test-py311
          - test-py312
          - test-py313
          - test-min-deps
        include:
          - os: macos-latest
            environment: test-py312
          - os: windows-latest
            environment: test-py312
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - uses: prefix-dev/setup-pixi@v0.10.1
        with:
          pixi-version: v0.77.0
          environments: ${{ matrix.environment }}
          log-level: vvv
          locked: true

      - name: setup matplotlib (Windows)
        if: startsWith(runner.os, 'Windows')
        run: |
          if not exist %userprofile%\.matplotlib\ ( mkdir %userprofile%\.matplotlib\ )
          echo backend: Agg > %userprofile%\.matplotlib\matplotlibrc
        shell: cmd

      - name: run pytest
        run: pixi run -e ${{ matrix.environment }} pytest --slow --junit-xml pytest.xml

      - name: Upload Test Results
        if: always() && matrix.environment == 'test-py310' && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v7
        with:
          name: Unit Test Results
          path: pytest.xml

      - name: test installable quality standard from template repository
        if: matrix.environment == 'test-py310' && matrix.os == 'ubuntu-latest'
        run: pixi run -e ${{ matrix.environment }} test_extra

      - name: coverage xml (combination is performed by pytest-cov)
        if: matrix.environment == 'test-py310' && matrix.os == 'ubuntu-latest'
        run: pixi run -e ${{ matrix.environment }} coverage_xml

      - name: codecov.io
        if: matrix.environment == 'test-py310' && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v6.0.1
