name: vulture
on: [push]

jobs:
  test:
    name: vulture
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Include $CONDA in $PATH
      run: echo ::add-path::$CONDA/bin
    - name: Print conda info
      run: conda info -a
    - name: Create conda environment
      run: conda env create -f ./environment.yml
    - name: Run vulture
      run: |
        source activate weldx
        vulture . --exclude weldx/asdf/,versioneer.py,weldx/_version.py,*__init__.py